name: build nico
on:
    push:
    pull_request:
        types: [opened, reopened, review_requested]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [19.0.0]

        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PAT }}
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install yarn
              run: npm i -g yarn

            - name: Install deps
              run: yarn install --immutable --immutable-cache --check-cache

            - name: Compiles to ts
              run: yarn build

            - name: Create report file
              run: date +%s > .lastcommit

            - name: Commit build
              run: |
                  git config --global user.name 'Mantou1233'
                  git config --global user.email 'Mantou1233@users.noreply.github.com'
                  git add -A
                  git commit -am "[no ci] Automated build"
                  git push
